### PR TITLE
Possible mistake in wezterm repo URL

### PR DESCRIPTION
**Pull request by antibaben**
Changing ssh repo URL to https to prevent crashing on permission denied.

### CODE REVIEW

**Comment by rootiest** [comment]
Ah, yeah this should work assuming you have set up ssh credentials with github.

But considering it's the only one that was configured that way and there's really no major reason to use ssh over https
this seems like a reasonable change.

Thanks for catching that!

**Comment by antibaben** [comment]
Thanks. Just for learning purposes, how should I come about setting up ssh credentials? I'm still learning to work with submodules and other submodules are giving me same cloning issues.

**Comment by rootiest** [comment]
> how should I come about setting up ssh credentials?

[Github has it documented here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)

You should be able to get it all working following those steps.

I would recommend checking out [github-cli](https://cli.github.com/) if you can install it as it makes some of these processes a little easier in my experience.

**Comment by antibaben** [comment]
Thanks, I've managed to solve my cloning issues related to ssh authentication, but now i'm getting a different error:

```
Submodule path 'home/dot_config/tmux': checked out '70da64e637c97b78071f641ff2a27f1dcb15c387'
fatal: No url found for submodule path 'home/dot_config/tmux/.tmux/plugins/tpm' in .gitmodules
fatal: Failed to recurse into submodule path 'home/dot_config/tmux'
chezmoi: git: exit status 128
```

Should I start an issue?

**Comment by rootiest** [comment]
Yeah I think so. I suspect this is because the tmux config is pulled in by a submodule but also contains its own submodules.

I'm going to have to look into that as I don't know if it will be straightforward to fix.

Go ahead and open an issue but give me a few days to get into it as I am going to be away until next week.

**Comment by antibaben** [comment]
Okay, althought it seems issues aren't setup for this repo or at least I'm not able to open one. I'll hit you up in a week through this mean if I can't manage to open an issue today.

**Comment by rootiest** [comment]
> issues aren't setup for this repo or at least I'm not able to open one

oops. should work now!

**Pull request merged**
